import React, { useState, useEffect } from 'react';
import API from '../services/api';
import { useNotification } from '../context/NotificationContext';
import { PieChart, Download, Plus } from 'lucide-react';

const Reports = () => {
  const { addToast } = useNotification();
  const [reports, setReports] = useState([
    { _id: '1', title: 'Semester 5 Overall Academic Performance Report', category: 'Academic', generatedBy: 'Admin', createdAt: '2026-07-20' },
    { _id: '2', title: 'Monthly Department Attendance Audit - CSE', category: 'Attendance', generatedBy: 'HOD CSE', createdAt: '2026-07-15' },
    { _id: '3', title: 'Faculty Workload & Credit Allocation Summary', category: 'Faculty', generatedBy: 'Academic Cell', createdAt: '2026-07-10' }
  ]);

  const [title, setTitle] = useState('');
  const [category, setCategory] = useState('Academic');

  useEffect(() => {
    const fetchReports = async () => {
      try {
        const res = await API.get('/reports');
        if (res.data && res.data.length > 0) setReports(res.data);
      } catch (err) {
        console.log('Using local reports state');
      }
    };
    fetchReports();
  }, []);

  const handleGenerate = async (e) => {
    e.preventDefault();
    if (!title) return;
    try {
      const res = await API.post('/reports', { title, category });
      setReports(prev => [res.data, ...prev]);
      addToast('New report generated successfully!', 'success');
      setTitle('');
    } catch (err) {
      setReports(prev => [{ _id: Date.now(), title, category, generatedBy: 'Admin', createdAt: new Date().toISOString().split('T')[0] }, ...prev]);
      addToast('New report generated!', 'success');
      setTitle('');
    }
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
      <div>
        <h1 style={{ fontSize: '1.5rem', fontWeight: 800, display: 'flex', alignItems: 'center', gap: '8px' }}>
          <PieChart color="#2563eb" /> System Analytical Reports
        </h1>
        <p style={{ color: 'var(--text-muted)', fontSize: '0.875rem' }}>Generate and download institutional academic, attendance, and financial reports</p>
      </div>

      <form onSubmit={handleGenerate} className="glass-card" style={{ padding: '1.25rem', display: 'flex', gap: '1rem', flexWrap: 'wrap', alignItems: 'center' }}>
        <input
          type="text"
          placeholder="Report Title (e.g. Annual Placement & Result Analysis)..."
          value={title}
          onChange={e => setTitle(e.target.value)}
          required
          style={{ flex: 1, minWidth: '280px', padding: '0.6rem 1rem', borderRadius: '8px', border: '1px solid var(--border-color)', background: 'var(--bg-primary)' }}
        />
        <select value={category} onChange={e => setCategory(e.target.value)} style={{ padding: '0.6rem 1rem', borderRadius: '8px', border: '1px solid var(--border-color)', background: 'var(--bg-surface)' }}>
          <option value="Academic">Academic</option>
          <option value="Attendance">Attendance</option>
          <option value="Marks">Marks</option>
          <option value="Faculty">Faculty</option>
        </select>
        <button type="submit" style={{ display: 'flex', alignItems: 'center', gap: '6px', background: '#2563eb', color: '#fff', border: 'none', padding: '0.6rem 1.25rem', borderRadius: '8px', fontWeight: 700, cursor: 'pointer' }}>
          <Plus size={16} /> Generate Report
        </button>
      </form>

      <div className="glass-card" style={{ padding: '1.25rem' }}>
        <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.875rem' }}>
          <thead>
            <tr style={{ borderBottom: '2px solid var(--border-color)', textAlign: 'left', color: 'var(--text-muted)' }}>
              <th style={{ padding: '0.75rem' }}>TITLE</th>
              <th style={{ padding: '0.75rem' }}>CATEGORY</th>
              <th style={{ padding: '0.75rem' }}>GENERATED BY</th>
              <th style={{ padding: '0.75rem' }}>DATE</th>
              <th style={{ padding: '0.75rem' }}>DOWNLOAD</th>
            </tr>
          </thead>
          <tbody>
            {reports.map(r => (
              <tr key={r._id} style={{ borderBottom: '1px solid var(--border-color)' }}>
                <td style={{ padding: '0.75rem', fontWeight: 700 }}>{r.title}</td>
                <td style={{ padding: '0.75rem' }}>
                  <span style={{ padding: '3px 8px', borderRadius: '10px', background: '#eff6ff', color: '#1d4ed8', fontSize: '0.75rem', fontWeight: 700 }}>
                    {r.category}
                  </span>
                </td>
                <td style={{ padding: '0.75rem' }}>{r.generatedBy}</td>
                <td style={{ padding: '0.75rem', color: 'var(--text-muted)' }}>{r.createdAt ? String(r.createdAt).split('T')[0] : '2026-07-22'}</td>
                <td style={{ padding: '0.75rem' }}>
                  <button onClick={() => addToast(`Downloading report PDF for ${r.title}`, 'info')} style={{ display: 'flex', alignItems: 'center', gap: '4px', background: '#2563eb', color: '#fff', border: 'none', padding: '4px 10px', borderRadius: '6px', cursor: 'pointer', fontSize: '0.75rem' }}>
                    <Download size={14} /> PDF
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
};

export default Reports;
